apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whodb.fullname" . }}
  labels:
    {{- include "whodb.labels" . | nindent 4 }}
data:
  {{- range $key, $item := .Values.profiles }}
  {{ $data := $item | toJson | b64enc | quote }}
  {{ printf "%s: %s" $key $data }}
  {{- end }}
