apiVersion: v2
name: dashy
description: A Helm chart for dashy dashboard

type: application
version: 0.1.3

appVersion: "2.1.1"

keywords:
  - dashboard
home: https://dashy.to/
icon: https://dashy.to/img/dashy.png
sources:
  - https://github.com/dshemin/charts
maintainers:
  - name: dshemin
    email: me@shemindmitry.tech
