name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: whodb
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: whodb
          repository: dshemin
          tag: 0.1.0
          registry: ghcr.io
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          update_dependencies: "true"
